version: '3.3'

services:
  db:
    image: mysql:5.7
    restart: always
    env_file: .env
    environment:
      MYSQL_USER: $DB_USER
      MYSQL_DATABASE: $DATABASE
      MYSQL_PASSWORD: $PASSWORD
      MYSQL_ROOT_PASSWORD: $PASSWORD
    ports:
      -   $PORT:$PORT
    expose: 
      - $PORT
    volumes: 
      - my-db:/var/lib/mysql
volumes:
  my-db: